name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        uses: kivy/kivy-ci-docker-action@master
        with:
          requirements: python3,kivy,kivymd
          arch: arm64-v8a,armeabi-v7a
          bootstrap: sdl2

      - uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
